#!/bin/sh

blkdev=`dirname $DEVPATH`
device=`basename $DEVPATH`
hdorsd=`echo "$device" | grep -E '[sh]d*|mmcblk0*' `

. /lib/functions.sh
. /lib/functions/system.sh


[ -n "$hdorsd" ] && {
    case "$ACTION" in
        add)

	    #if have gl nas ipk, give gl nas mount disk
	    if [ -e /usr/bin/gl_nas_sys ]
	    then
		exit 1
	    fi

            #when boot, the devices may not be ready, strange
            sleep 5
            #first time, wait unit the jffs is built
            if [ -z  "$(mount |grep 'overlayfs:/overlay')" ]
            then
				echo "$DEVPATH" >/tmp/mount.tmp
				echo "$ACTION" >>/tmp/mount.tmp
				exit 1
                #sleep 40 #this caused the wireless configure cannot be built correctly, we disable this and should be fixed later
            fi
            sync=sync
            mmcblk0=`echo "$device" |grep 'mmcblk0'`
            if [ -n "$mmcblk0" ]; then
                sync=async
            fi
            s=`/usr/sbin/blkid /dev/$device|sed -n 's/.* TYPE="\([^"]*\)".*/\1/p'`
            label=$device


            if [ "$s" != 'vfat' -a "$s" != 'ntfs' -a "$s" != 'ext2' -a "$s" != "ext3" -a "$s" != "ext4" -a "$s" != "exfat" ];then
                  return;
            fi

            mkdir -p "/mnt/$label"
			
            if [ "$s" = 'vfat' -o "$s" = 'exfat' ];then
                mount -t $s -o utf8,rw,$sync,fmask=0000,dmask=0000 /dev/$device "/mnt/$label"
            fi

            if [ "$s" = 'ntfs' ];then
                mount -t ntfs-3g -o utf8 /dev/$device "/mnt/$label"
            fi

            if [ "$s" = 'ext2' -o "$s" = 'ext3' -o "$s" = 'ext4' ];then
                mount -t ext4 -o rw,$sync /dev/$device "/mnt/$label"
                chmod 777 "/mnt/$label"
                chown root:root "/mnt/$label"
            fi

            #if [ "$s" = "exfat" ]; then
            #    mount -t exfat -o utf8,rw,$sync /dev/$device "/mnt/$label"
            #fi

            sleep 5

            download_root=$(uci get glconfig.download.root)
            if [ -z "$download_root" ]; then
                uci set glconfig.download.root="/mnt/$label"
                uci commit glconfig
            fi

            samba=`opkg list-installed | grep samba36-server`
            if [ -n "$samba" ];then
                    path=`uci -q get samba.@sambashare[0].path`
                    if [ -z "$path" ];then
                            uci -q set samba.@sambashare[0].path="/mnt/$label"
                            uci commit samba
                            /etc/init.d/samba restart
                    fi
            fi

            ;;

        remove)
			echo "----mount: remove $device" > /dev/console
            folder="$(grep /dev/$device /etc/mtab |awk '{print $2}')"
            procs=$(fuser -m "/mnt/$folder")

            samba=`opkg list-installed | grep samba36-server`
            if [ -n "$samba" ];then
                    path=`uci -q get samba.@sambashare[0].path`
                    if [ -n "$path" -a "$path" = "$folder" ];then
                            uci -q del samba.@sambashare[0].path
                            uci commit samba
                            /etc/init.d/samba restart
                    fi
            fi

            if [ "${#procs}" -lt 10 ]; then
                echo "$procs" | xargs kill -9
            fi
            umount -l "$folder"
            rmdir "$folder"
            ;;
    esac
    #restart lighttpd for fastcgi reset
    #/etc/init.d/lighttpd restart
}
