#!/bin/sh

if [ -f /etc/config/sqm ] && [ "$(uci -q get sqm.@service[-1].inited)" != "1" ]; then
    uci add sqm service
    uci set sqm.@service[-1].inited='1'
    uci set sqm.@queue[0].interface="br-lan"
    uci set sqm.@queue[0].upload="0"
    uci set sqm.@queue[0].download="0"

    uci commit sqm
fi
cp /etc/piece_of_cake.qos /usr/lib/sqm/piece_of_cake.qos
cp /etc/simple.qos /usr/lib/sqm/simple.qos

exit 0
