#!/bin/sh

. /lib/functions/gl_util.sh

firewall_wan_all_set() {
    if ! uci show firewall | grep -q "firewall.@zone.*.name='wan_all'"; then
        uci add firewall zone
		uci set firewall.@zone[-1].name='wan_all'
		uci set firewall.@zone[-1].input='REJECT'
		uci set firewall.@zone[-1].output='ACCEPT'
		uci set firewall.@zone[-1].forward='REJECT'
		uci set firewall.@zone[-1].masq='0'
        uci commit firewall
    fi
}

model=$(get_model)
case "$model" in
	"e5800")
		firewall_wan_all_set
	;;
esac

