#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.glblock
	set firewall.glblock=include
	set firewall.glblock.type=script
	set firewall.glblock.path=/usr/bin/gl_block.sh
	set firewall.glblock.reload=1
	commit firewall
EOF
exit 0
