#!/bin/sh

. /lib/functions/gl_util.sh

check_or_reset_interface() {
    local section="$1"
    local proto
    proto="$(uci -q get network.${section}.proto)"

    if [ -z "$proto" ]; then
        create_interface "$section"
    elif [ "$proto" != "rmnet" ]; then
        uci -q delete network.${section}
        create_interface "$section"
    fi
}

create_interface() {
    local section="$1"

    if [ "$section" = "modem_cpu" ]; then
        uci set network.modem_cpu='interface'
        uci set network.modem_cpu.proto='rmnet'
        uci set network.modem_cpu.profile='1'
        uci set network.modem_cpu.downstream='lan'
        uci set network.modem_cpu.type='internet'
        uci set network.modem_cpu.bind='0'
        uci set network.modem_cpu.ipv6='0'
        uci set network.modem_cpu.defaultroute='1'
        uci set network.modem_cpu.lockmtu='0'
        uci set network.modem_cpu.allow_dial='0'
    elif [ "$section" = "modem_cpu_6" ]; then
        uci set network.modem_cpu_6='interface'
        uci set network.modem_cpu_6.proto='rmnet'
        uci set network.modem_cpu_6.profile='1'
        uci set network.modem_cpu_6.downstream='lan'
        uci set network.modem_cpu_6.type='internet'
        uci set network.modem_cpu_6.bind='0'
        uci set network.modem_cpu_6.ipv6='1'
        uci set network.modem_cpu_6.defaultroute='1'
        uci set network.modem_cpu_6.lockmtu='0'
    fi
}



model=$(get_model)
case "$model" in
	"e5800")
		check_or_reset_interface "modem_cpu"
		check_or_reset_interface "modem_cpu_6"
		uci commit network
		exit 0
	;;
esac
