#!/bin/sh
. /lib/functions.sh
. /lib/netifd/netifd-proto.sh
. /usr/share/libubox/jshn.sh
. /lib/functions/modem.sh

check_network_ready() {
    local bus="$1"
    local netdev="$2"
    local timeout=3
    local interval=1
    local elapsed=0

    while [ $elapsed -lt $timeout ]; do
        local status
        ping 8.8.8.8 -c 1 -W 1 -I "$netdev"> /dev/null 2>&1
        if [ $? -ne 0 ]; then
            sleep $interval
            #echo "$process_name elapsed time:$elapsed s, waiting for network ready on bus:$bus"  > /dev/kmsg
            elapsed=$((elapsed + interval))
            continue
        else
            log_info "$process_name Network is ready on bus:$bus"
            support=$(cat /etc/config/cellular/slot_map.json | jsonfilter -e '@.slot_multi_priority.slot_'"$bus"'')
            [ -n "$support" ] && {
                ubus call cellular.modem clean_switch_count "{\"bus\":\"$bus\"}"
            }
            #echo "$process_name Network is ready on bus:$bus"  > /dev/kmsg
            return 0
        fi

    done
    #echo "$process_name Network is not ready on bus:$bus after $timeout seconds"  > /dev/kmsg
    ubus call cellular.failover switch_event "{\"event\":\"NETWORK_ERROR\",\"slot\":0,\"bus\":\"$bus\"}"
    return 1
}

set_log_level "$(get_modem_log_level)"

[ -n "$(echo $INTERFACE| grep modem | grep -v "_4" | grep -v "_6")" ] || exit 0
[ "$STATUS" = "offline" ] || exit 0

bus="${INTERFACE#*modem_}"
if [ "$bus" != "cpu" ];then
    bus=$(uci -q get network.$INTERFACE.bus)
fi

device=$(ubus call network.interface.$INTERFACE status| jsonfilter -e @.l3_device)
process_name=$(basename "$0")
#echo "$process_name interface: $INTERFACE" "bus: $bus" "device: $device" > /dev/kmsg

log_debug $LINENO "$process_name modem" "iface:$INTERFACE status:$STATUS"
(check_network_ready "$bus" "$device"; exit 0) &
