#!/bin/sh

[ "$ACTION" = ifup -o "$ACTION" = ifdown -o "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

/etc/init.d/firewall enabled || exit 0

fw3 -q network "$INTERFACE" >/dev/null 

logger -t firewall "Reloading firewall due to $ACTION of $INTERFACE ($DEVICE)"
if [ $INTERFACE = "wan6" ]; then
    sleep 1 && fw3 -q reload&
else
    fw3 -q reload
fi
