#!/bin/sh /etc/rc.common

START=99

SERVICE=apcli_detectd

start() {
	if [ -f /usr/bin/$SERVICE ]; then
        	echo "run apcli_detectd service......"
        	service_start /usr/bin/$SERVICE 3 1
	fi
}
stop() {
	if [ -f /usr/bin/$SERVICE ]; then
        	service_stop /usr/bin/$SERVICE
	fi
}

