#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=90

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	touch /tmp/uci_commit_lock
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	rm -f /tmp/uci_commit_lock
	uci commit
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc

	mkdir -p /var/lock
	chmod 1777 /var/lock
	mkdir -p /var/log
	mkdir -p /var/run
	mkdir -p /var/state
	mkdir -p /var/tmp
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	mkdir -p /tmp/resolv.conf.d
	touch /tmp/resolv.conf.d/resolv.conf.auto
	ln -sf /tmp/resolv.conf.d/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	grep -q bpf /proc/filesystems && /bin/mount -o nosuid,nodev,noexec,noatime,mode=0700 -t bpf bpffs /sys/fs/bpf
	grep -q pstore /proc/filesystems && /bin/mount -o noatime -t pstore pstore /sys/fs/pstore
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/sbin/kmodloader

	[ ! -f /etc/config/wireless ] && {
		/sbin/wifi detect
		# compat for bcm47xx and mvebu
		sleep 1
	}
	touch /tmp/wifi_reload_lock

	/bin/config_generate
	uci_apply_defaults
	sync

	if [ -e /sys/devices/platform/11200000.xhci/RG_USB20_DISCTH ]; then
		echo "2 0 4b0101" > /sys/devices/platform/11200000.xhci/RG_USB20_DISCTH
	fi

	if [ -e /sys/devices/platform/11190000.xhci/RG_USB20_DISCTH ]; then
		echo "2 0 4b0101" > /sys/devices/platform/11190000.xhci/RG_USB20_DISCTH
	fi
	
	# temporary hack until configd exists
	/sbin/reload_config
}
