#!/bin/sh /etc/rc.common

START=10

USE_PROCD=1
PROG=/usr/bin/fcgiwrap

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -c 4 -s unix:/var/run/fcgiwrap.socket
	procd_set_param respawn 3600 2 0
	procd_close_instance
}

stop_service() {
	killall -9 "$PROG"
}
