#!/bin/sh  /etc/rc.common

USE_PROCD=1

start_service(){
    local enable=$(uci -q get gl-cloud.@cloud[0].enable)
    [ "$enable" != "1" ] && return 0

    procd_open_instance
    procd_set_param command /usr/bin/eco /usr/bin/alarm_event_report
    procd_set_param respawn 3600 2 0
    procd_close_instance
}
