#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

. /lib/functions/gl_util.sh

start_service() {
    local server=$(uci -q get gl-cloud.@cloud[0].server)
    local enable=$(uci -q get gl-cloud.@cloud[0].enable)

    mkdir -p /var/run/cloud

    [ "$enable" != "1" ] && return 0

    if [ ! -f /etc/glversion ]; then
        logger -t gl-cloud -p user.warn "/etc/glversion not found!!!, refusing to start gl-cloud"
        return 1
    fi

    procd_open_instance
    procd_set_param command /usr/bin/eco /usr/bin/gl-cloud
    procd_set_param respawn 3600 5 0
    local vpn_group=$(get_vpn_group)
    [ -n "$vpn_group" ] && procd_set_param group $vpn_group
    procd_close_instance

    /etc/init.d/gl-alarm start
}


stop_service() {
    if [ -f /usr/bin/mptun ]; then
        iptables -t nat -F SDWAN_IP_MAPPING 2>/dev/null
        iptables -t nat -F SDWAN_IP_MAPPING_SNAT 2>/dev/null

        iptables -t nat -D PREROUTING -j SDWAN_IP_MAPPING 2>/dev/null
        iptables -t nat -D OUTPUT -j SDWAN_IP_MAPPING 2>/dev/null
        iptables -t nat -D POSTROUTING -j SDWAN_IP_MAPPING_SNAT 2>/dev/null

        iptables -t nat -X SDWAN_IP_MAPPING 2>/dev/null
        iptables -t nat -X SDWAN_IP_MAPPING_SNAT 2>/dev/null

        lanmark=$(uci get mptun.global.lanmark 2>/dev/null || echo "0x4")
        iptables -t mangle -D FORWARD -i br-lan -o br-lan -m comment --comment SDWAN_IP_MAPPING_MARK -j MARK --set-xmark $lanmark/$lanmark 2>/dev/null
    fi
    rm /etc/mptun/mpnet.json 2>/dev/null
    rm /etc/mptun/mpnet_conf 2>/dev/null
    [ -n "$(pgrep gl-p2p-daemon)" ] && kill $(pgrep gl-p2p-daemon) 2>/dev/null
    /etc/init.d/gl-alarm stop
}

