#!/bin/sh /etc/rc.common

START=10
STOP=10

USE_PROCD=1

start_service() {
	[ -f /etc/nginx/error.log ] && {
		mkdir -p /var/log/nginx
		cat /etc/nginx/error.log > /var/log/nginx/error.log
	}

	procd_open_instance
	procd_set_param command eco /usr/sbin/gl-ngx-session
	procd_set_param respawn 5 5 -1
	procd_close_instance
}

stop_service() {
	cp /var/log/nginx/error.log /etc/nginx/error.log
}
