#!/bin/sh /etc/rc.common
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99
STOP=10

USE_PROCD=1

DB_PATH="/etc/oui-tertf/client.db"

start_service() {
    mkdir -p /etc/oui-tertf/

    procd_open_instance
    procd_set_param respawn
    procd_set_param stderr 1
    procd_set_param command /usr/bin/lua /usr/bin/gl_clients_update
    procd_close_instance
}

stop_service() {
    if [ -f "$DB_PATH" ];then
        ubus call gl-clients sync
    fi
}
