#!/bin/sh /etc/rc.common
START=95
STOP=10

PROG=/usr/lib/gl_ddns/dynamic_dns_updater.sh

. /lib/functions/gl_util.sh
vpn_group=$(get_vpn_group)
if [ -n "$vpn_group" ];then
    PROG="sudo -g $vpn_group /usr/lib/gl_ddns/dynamic_dns_updater.sh"
else
    PROG=/usr/lib/gl_ddns/dynamic_dns_updater.sh
fi



boot() {
    return 0
}

reload() {
    $PROG -- reload
    return 0
}

restart() {
    $PROG -- stop
    sleep 1 # give time to shutdown
    enable=`uci -q get gl_ddns.glddns.enabled`
    if [ "$enable" = 1 ];then
        $PROG -- start
    fi
}

start() {
    enable=`uci -q get gl_ddns.glddns.enabled`
    if [ "$enable" = 1 ];then
        $PROG -- start
    fi
}

stop() {
    $PROG -- stop
    return 0
}

ddns_shutdown() {
    ddns_rundir=$(uci -q get gl_ddns.global.ddns_rundir)
    if [ "$ddns_rundir" = "" ];then
        ddns_rundir="/var/run/ddns"
    fi
    pid=$(cat ${ddns_rundir}/*.pid 2>/dev/null | tr '\n' ' ')
    kill $pid
}

shutdown() {
    ddns_shutdown
}
