#!/bin/sh /etc/rc.common
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99

app=/usr/bin/gl_nas_sys

#use proc to exec cmd
USE_PROCD=1

start_service() {
	echo "start app = $app"

	#service_start $app
        nas_enable=$(uci -q get nas.conf.gl_nas_sys_enable)
	if ! [ -z $nas_enable ]; then
		if [ "$nas_enable" -eq "1" ]; then
			echo "=== nas enable"

			procd_open_instance "gl_nas_sys_up"
			#procd_set_param command $app -p 6002
			procd_set_param command $app -e up
			procd_set_param respawn ${respawn_threshold:-3600} ${respawn_threshold:-3} ${respawn_threshold:-30}
			procd_close_instance

		fi
	fi

}

stop_service()
{
	echo "stop up app = $app"
}


