#!/bin/sh /etc/rc.common
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=40

app=/usr/bin/gl_nas_diskmanager

#use proc to exec cmd
#USE_PROCD=1

start() {
	echo "start app = $app"

	#this method start, affect lighttpd start
	#service_start $app
	$app > /dev/null &
}

stop()
{
	echo "stop app = $app"
	kill -9 $(pgrep -f $app) 2>/dev/null
	#service_stop $app
}


