#!/bin/sh /etc/rc.common

# shellcheck disable=SC3003

START=95
USE_PROCD=1

IP4="ip -4"
IP6="ip -6"

WG=/usr/bin/wg

wireguard_setup_peer() {
	local section="$1"

	local endpoint
	local keepalive
	local public_key
	local allowed_ips
	local preshared_key

	config_get endpoint      "${section}" "endpoint"
	config_get keepalive     "${section}" "keepalive"
	config_get public_key    "${section}" "public_key"
	config_get allowed_ips   "${section}" "allowed_ips"
	config_get preshared_key "${section}" "preshared_key"

	# Peer configuration
	echo "" >> "${wg_cfg}"
	echo "[Peer]" >> "${wg_cfg}"
	echo "PublicKey = ${public_key}" >> "${wg_cfg}"
	[ -n "${preshared_key}" ] && echo "PresharedKey = ${preshared_key}" >> "${wg_cfg}"
	[ -n "${endpoint}" ] && echo "Endpoint = ${endpoint}" >> "${wg_cfg}"
	[ -n "${keepalive}" ] && echo "PersistentKeepalive = ${keepalive}" >> "${wg_cfg}"

	for allowed_ip in ${allowed_ips}; do
		echo "AllowedIPs = ${allowed_ip}" >> "${wg_cfg}"
	done
}

wireguard_setup_interface() {
	local config="$1"

	local wg_dir="/tmp/wireguard"
	local wg_cfg="${wg_dir}/${config}.conf"

	local mtu
	local metric
	local fwmark
	local ipaddr
	local private_key
	local listen_port

	config_get mtu         "${config}" "mtu" "1320"
	config_get metric      "${config}" "metric" "80"
	config_get fwmark      "${config}" "fwmark"
	config_get address     "${config}" "address"
	config_get private_key "${config}" "private_key"
	config_get listen_port "${config}" "listen_port"

	ip link del dev wg1 2>/dev/null
	ip link add dev wg1 type wireguard

	[ -n "${mtu}" ] && ip link set mtu "${mtu}" dev wg1

	# Add ip addresses
	for addr in ${address}; do
		case "${addr}" in
		*:*/*)
			$IP6 address add dev wg1 ${addr%%/*}/${addr##*/} > /dev/null 2>&1
			;;
		*.*/*)
			$IP4 address add dev wg1 ${addr%%/*}/${addr##*/} > /dev/null 2>&1
			;;
		*:*)
			$IP6 address add dev wg1 ${addr%%/*}/128 > /dev/null 2>&1
			;;
		*.*)
			$IP4 address add dev wg1 ${addr%%/*}/32 > /dev/null 2>&1
			;;
		esac
	done

	# Generate configuration file
	umask 077
	mkdir -p "${wg_dir}"

	echo "[Interface]" > "${wg_cfg}"
	echo "PrivateKey = ${private_key}" >> "${wg_cfg}"
	[ -n "$listen_port" ] && echo "ListenPort = ${listen_port}" >> "${wg_cfg}"
	[ -n "$fwmark" ] && echo "FwMark = ${fwmark}" >> "${wg_cfg}"

	config_foreach wireguard_setup_peer peer

	# Apply configuration file
	${WG} setconf wg1 "${wg_cfg}"
	if [ $? -ne 0 ]; then
		ip link del dev wg1 > /dev/null 2>&1
		rm -f "${wg_cfg}" > /dev/null 2>&1
		exit 1
	fi

	# Delete temporary configuration file
	rm -f "${wg_cfg}" > /dev/null 2>&1

	# Setup WireGuard interface
	ip link set up dev wg1
	sleep 1

	# Add ip route
	wg show wg1 allowed-ips | sort -nr -k 2 -t / | \
		while IFS=$'\t' read -r key addresses; do
			for addr in ${addresses}; do
				case "${addr}" in
				*:*/*)
					$IP6 route add ${addr%%/*}/${addr##*/} dev wg1 metric ${metric} > /dev/null 2>&1
					;;
				*.*/*)
					$IP4 route add ${addr%%/*}/${addr##*/} dev wg1 metric ${metric} > /dev/null 2>&1
					;;
				*:*)
					$IP6 route add ${addr%%/*}/128 dev wg1 metric ${metric} > /dev/null 2>&1
					;;
				*.*)
					$IP4 route add ${addr%%/*}/32 dev wg1 metric ${metric} > /dev/null 2>&1
					;;
				esac
			done
		done
}

cleanup() {
	for pid in `pidof "echo_server"`; do                
		kill -KILL ${pid}
	done
}

flush_rules() {
	uci -q batch <<-EOF >/dev/null
		delete network.wg_s2s
		delete firewall.wg_s2s
		delete firewall.s2s_lan
		delete firewall.s2s_wan
		delete firewall.lan_s2s
		delete firewall.wan_s2s
		commit network
		commit firewall
	EOF
}

ipt_filter() {
	uci -q batch <<-EOF >/dev/null
		set network.wg_s2s=interface
		set network.wg_s2s.device='wg1'
		set network.wg_s2s.proto='none'
		set firewall.wg_s2s=zone
		set firewall.wg_s2s.name='wg_s2s'
		set firewall.wg_s2s.input='ACCEPT'
		set firewall.wg_s2s.forward='ACCEPT'
		set firewall.wg_s2s.output='ACCEPT'
		set firewall.wg_s2s.device='wg1'
		set firewall.wg_s2s.network='wg_s2s'
		set firewall.s2s_lan=forwarding
		set firewall.s2s_lan.dest='lan'
		set firewall.s2s_lan.src='wg_s2s'
		set firewall.s2s_wan=forwarding
		set firewall.s2s_wan.dest='wan'
		set firewall.s2s_wan.src='wg_s2s'
		set firewall.lan_s2s=forwarding
		set firewall.lan_s2s.dest='wg_s2s'
		set firewall.lan_s2s.src='lan'
		set firewall.wan_s2s=forwarding
		set firewall.wan_s2s.dest='wg_s2s'
		set firewall.wan_s2s.src='wan'
		commit network
		commit firewall
	EOF
}

service_triggers()
{
	procd_add_reload_trigger "gl_s2s"
}

start_service() {
	local enable
	local firewall

	if ! command -v ${WG} > /dev/null 2>&1; then
		logger -t "wireguard" "error: missing wireguard-tools (${WG})"
		return 0
	fi

	config_load gl_s2s

	config_get enable global enable
	[ "$enable" = "1" ] || return 0

	cleanup

	config_get firewall global firewall
	[ "$firewall" = "1" ] && ipt_filter
	/etc/init.d/network reload

	config_foreach wireguard_setup_interface interface

	# update alive status to good-cloud
	ubus call gl-cloud alive 2>/dev/null
}

stop_service() {
	local firewall
	config_load gl_s2s
	config_get firewall global firewall
	[ "$firewall" = "1" ] && flush_rules

	ip link del dev wg1 > /dev/null 2>&1

	# update alive status to good-cloud
	ubus call gl-cloud alive 2>/dev/null
}
