#!/bin/sh /etc/rc.common

START=80
USE_PROCD=1

. /etc/gl_screen/scripts/common.sh

start_service() {
    gen_screen_config
    procd_open_instance
    procd_set_param nice -20
    procd_set_param command /usr/bin/gl_screen -c $output_dir
    procd_set_param respawn 1 5 -1
    procd_close_instance
}

reload_service() {
    gen_screen_config
    ubus call gl_screen set '{"method": "reload"}'
}


