#!/bin/sh /etc/rc.common

USE_PROCD=1
START=98

start_service() {
    local enable=$(uci -q get mptun.global.enable)

    [ "$enable" != "1" ] && return 0

    procd_open_instance
    procd_set_param command /usr/bin/eco /usr/bin/mpifd
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    local ifaces=$(cat /etc/iproute2/rt_tables |grep mptcp_|awk '{print $2}')

    local iface
    for iface in $ifaces; do
        ip rule del lookup $iface 2>/dev/null
    done
}

