#!/bin/sh /etc/rc.common

START=20

start() {

    [ -d "/etc/wireless/mediatek" ] || exit 0

    local enable=$(uci -q get mtkhnat.global.enable)

    [ "$enable" != "1" ] && enable=0
    echo $enable > /sys/kernel/debug/hnat/hook_toggle
}
