#!/bin/sh /etc/rc.common
START=90
STOP=10

USE_PROCD=1

stop_service() {
	rm /tmp/sms_manager_port
}

start_service() {
        procd_open_instance
        procd_set_param command "/usr/bin/sms_manager"
        procd_set_param respawn
        procd_close_instance
}
