#!/bin/sh /etc/rc.common
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99

app=/usr/bin/webdav_ser

#use proc to exec cmd
USE_PROCD=1

start_service() {
	echo "start app = $app"

	#service_start $app
        webdav_enable=$(uci -q get nas.conf.webdav_enable)
	if ! [ -z $webdav_enable ]; then
		if [ "$webdav_enable" -eq "1" ]; then
			echo "=== webdav enable"

			procd_open_instance "webdav_ser"
			procd_set_param command "/usr/bin/webdav_ser"
			procd_close_instance

		fi
	fi

}

stop_service()
{
	echo "stop app = $app"
	#procd auto close app
}



