#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0

START=99

tm_path=/tmp/.testmode

invoke_msp_daemon() {
	if [ -f ${tm_path} ]; then
		ated
		telnetd
	fi
}


boot() {
	invoke_msp_daemon
}
