src/gz glinet_core https://fw.gl-inet.com/releases/v21.02-SNAPSHOT/mt798x/kmod-5.4.281/aarch64_cortex-a53/kmod-5.4
src/gz glinet_gli_pub https://fw.gl-inet.com/releases/v21.02-SNAPSHOT/mt798x/packages/aarch64_cortex-a53/glinet
src/gz glinet_gli_packages https://fw.gl-inet.com/releases/v21.02-SNAPSHOT/mt798x/packages/aarch64_cortex-a53/packages
