
local M = {
    VPN_ERR_PARAM_MISSING                   = 20001011,
    VPN_ERR_PARAM_INVALIED                  = 20001012,
    VPN_ERR_PARAM_HAS_RCE_RISK              = 20001013,
    VPN_ERR_GET_CONF_FILE_FAIL              = 20001014,
    VPN_ERR_GET_CONF_FAIL                   = 20001015,
    VPN_ERR_CONF_SECTION_NOT_EXIST          = 20001016,
    VPN_ERR_TERGET_IF_ALREADY_RUN           = 20001017,
    VPN_ERR_NO_EXECUTE_PROGRAM              = 20001018,
    VPN_ERR_NO_INIT_PROGRRAM                = 20001019,
    VPN_ERR_NO_KEY_FILE                     = 20001020,
    VPN_ERR_NO_CERT_FILE                    = 20001021,
    VPN_ERR_NO_OPENSSL_TOOL                 = 20001022,
    VPN_ERR_GEN_KEY_FAIL                    = 20001023,
    VPN_ERR_GEN_CERT_FAIL                   = 20001024,
    VPN_ERR_GET_LOCAL_IPV4_NET_FAIL         = 20001025,
    VPN_ERR_GET_LOCAL_IPV6_NET_FAIL         = 20001026,
    VPN_ERR_CONFLICT_WITH_LOCAL_ADDR_V4     = 20001027,
    VPN_ERR_CONFLICT_WITH_LOCAL_ADDR_V6     = 20001028,
    VPN_ERR_CLIENT_IF_CONFLICT              = 20001029,
    VPN_ERR_CLIENT_IS_RUNNING               = 20001030,
    VPN_ERR_SERVER_IS_RUNNING               = 20001031,
    VPN_ERR_SERVER_IF_CONFLICT              = 20001032,
    VPN_ERR_PORT_BE_USED                    = 20001033,
    VPN_ERR_FILE_IO_ERR                     = 20001034,
    VPN_ERR_FILE_NOT_EXIST                  = 20001035,
    VPN_ERR_UCI_INIT_FAIL                   = 20001036,
    VPN_ERR_CONFLICT_FUNC_EXIST             = 20001037,

    VPN_ERR_INVALID_LOGIN_INFO              = 20001100,
    VPN_ERR_UNKNOWN_PROVIDER                = 20001101,
    VPN_ERR_NO_PASSWD                       = 20001102,
    VPN_ERR_TO_MANY_CONF_ITEM               = 20001103,
    VPN_ERR_COUNTRY_COUNT_ZERO              = 20001104,
    VPN_ERR_ERR_AUTH_TYPE_VAL               = 20001105,
    VPN_ERR_INVALID_IP_ADDR                 = 20001106,
    VPN_ERR_DOWNLOAD_CONF_FAIL              = 20001107,
    VPN_ERR_GEN_PEER_IP_FAIL                = 20001108,

    VPN_ERR_DECOMPRESSION_FAILED            = 20001201,
    VPN_ERR_PROCESS_ALREADY_RUNNING         = 20001202,
    VPN_ERR_GROUP_AUTH_CONFLICT_WITH_USERS  = 20001203,
    VPN_ERR_NO_SERVER_PUBKEY_EXIST          = 20001204,
    VPN_ERR_REACH_KEY_LIMIT                 = 20001205,

    VPN_ERR_INVALID_PRIVATE_WG_KEY          = 20001206,
    VPN_ERR_PASSWORD_TOO_SHORT              = 20001207,
    VPN_ERR_USERNAME_HAS_BEEN_TOKEN         = 20001208,
    VPN_ERR_INVALID_USERNAME                = 20001209,
    VPN_ERR_REGISTER_ACCOUNT_FAIL           = 20001210,
    VPN_ERR_GET_PROVIDER_TOKEN_FAIL         = 20001211,
    VPN_ERR_REGISTER_PUBLIC_KEY_FAIL        = 20001212,
    VPN_ERR_VPN_CLIENT_CONNECT_FAIL         = 20001213,
    VPN_ERR_CONNECT_SERVER_FAIL             = 20001214,
    VPN_ERR_API_LIMIT_TRIGGERED             = 20001215,
    VPN_ERR_DEVICE_ACCOUNT_BINDING_FAIL     = 20001216,
    VPN_ERR_DEVICE_UNAUTHENTICATED          = 20001217,
    VPN_ERR_REACH_LOGIN_LIMIT               = 20001218,
    VPN_ERR_UPLOAD_FILE_TOO_LARGE           = 20001219,
    VPN_ERR_OPERATE_TOO_FREQUENT            = 20001220,
    VPN_ERR_EXTERNAL_SERVICE_UNAVAILABLE    = 20001221,
    VPN_ERR_TAP_S2S_MODE_CONFLICT           = 20001222,
    VPN_ERR_PROVIDER_MFA_REQUIRED           = 20001223,
    VPN_ERR_PROVIDER_OTP_INVALID            = 20001224,
}

local err_msg = {
    [M.VPN_ERR_PARAM_MISSING]                  = "parameter missing",
    [M.VPN_ERR_PARAM_INVALIED]                 = "invalid parameter",
    [M.VPN_ERR_PARAM_HAS_RCE_RISK]             = "parameter has rce risk",
    [M.VPN_ERR_GET_CONF_FILE_FAIL]             = "get configuration file failed",
    [M.VPN_ERR_GET_CONF_FAIL]                  = "get config data failed",
    [M.VPN_ERR_CONF_SECTION_NOT_EXIST]         = "config section not exist",
    [M.VPN_ERR_TERGET_IF_ALREADY_RUN]          = "target interface already running",
    [M.VPN_ERR_NO_EXECUTE_PROGRAM]             = "no execute program, maybe not install",
    [M.VPN_ERR_NO_INIT_PROGRRAM]               = "no init script",
    [M.VPN_ERR_NO_KEY_FILE]                    = "private key file not exist",
    [M.VPN_ERR_NO_CERT_FILE]                   = "public key file not exist",
    [M.VPN_ERR_NO_OPENSSL_TOOL]                = "no openssl tool, maybe not install",
    [M.VPN_ERR_GEN_KEY_FAIL]                   = "generate private key failed",
    [M.VPN_ERR_GEN_CERT_FAIL]                  = "generate public key failed",
    [M.VPN_ERR_GET_LOCAL_IPV4_NET_FAIL]        = "get local IPv4 address failed",
    [M.VPN_ERR_GET_LOCAL_IPV6_NET_FAIL]        = "get local IPv6 address failed",
    [M.VPN_ERR_CONFLICT_WITH_LOCAL_ADDR_V4]    = "the target address conflicts with local IPv4 address",
    [M.VPN_ERR_CONFLICT_WITH_LOCAL_ADDR_V6]    = "the target address conflicts with local IPv6 address",
    [M.VPN_ERR_CLIENT_IF_CONFLICT]             = "other vpn client is running",
    [M.VPN_ERR_CLIENT_IS_RUNNING]              = "vpn client is running",
    [M.VPN_ERR_SERVER_IS_RUNNING]              = "vpn server is running",
    [M.VPN_ERR_SERVER_IF_CONFLICT]             = "other vpn server is running",
    [M.VPN_ERR_PORT_BE_USED]                   = "the port is already occupied",
    [M.VPN_ERR_FILE_IO_ERR]                    = "file I/O error",
    [M.VPN_ERR_FILE_NOT_EXIST]                 = "file not exist",
    [M.VPN_ERR_UCI_INIT_FAIL]                  = "uci init failed",
    [M.VPN_ERR_CONFLICT_FUNC_EXIST]            = "features that conflict with vpn have been enabled",

    [M.VPN_ERR_INVALID_LOGIN_INFO]             = "invalid login info",
    [M.VPN_ERR_UNKNOWN_PROVIDER]               = "unknown provider",
    [M.VPN_ERR_NO_PASSWD]                      = "account has no password",
    [M.VPN_ERR_TO_MANY_CONF_ITEM]              = "too many configuration items",
    [M.VPN_ERR_COUNTRY_COUNT_ZERO]             = "the number of servers in the selected country is zero",
    [M.VPN_ERR_ERR_AUTH_TYPE_VAL]              = "error auth type",
    [M.VPN_ERR_INVALID_IP_ADDR]                = "invalid IP address",
    [M.VPN_ERR_DOWNLOAD_CONF_FAIL]             = "download configuration file failed",
    [M.VPN_ERR_GEN_PEER_IP_FAIL]               = "generate peer IP address failed",

    [M.VPN_ERR_DECOMPRESSION_FAILED]           = "decompression failed",
    [M.VPN_ERR_PROCESS_ALREADY_RUNNING]        = "process already running",
    [M.VPN_ERR_GROUP_AUTH_CONFLICT_WITH_USERS] = "group auth conflict with user's",
    [M.VPN_ERR_NO_SERVER_PUBKEY_EXIST]         = "server public key does not exist",
    [M.VPN_ERR_REACH_KEY_LIMIT]                = "reach key limit",

    [M.VPN_ERR_INVALID_PRIVATE_WG_KEY]         = "invalid private key",
    [M.VPN_ERR_PASSWORD_TOO_SHORT]             = "the password must be at least 8 characters",
    [M.VPN_ERR_USERNAME_HAS_BEEN_TOKEN]        = "the username has already been taken",
    [M.VPN_ERR_INVALID_USERNAME]               = "the username may only contain letters and numbers",
    [M.VPN_ERR_REGISTER_ACCOUNT_FAIL]          = "register new account failed",
    [M.VPN_ERR_GET_PROVIDER_TOKEN_FAIL]        = "get third part provider token fail",
    [M.VPN_ERR_REGISTER_PUBLIC_KEY_FAIL]       = "register public key fail",
    [M.VPN_ERR_VPN_CLIENT_CONNECT_FAIL]        = "vpn client failed to connect to server",
    [M.VPN_ERR_CONNECT_SERVER_FAIL]            = "get information from provider server failed",
    [M.VPN_ERR_API_LIMIT_TRIGGERED]            = "API limit triggered",
    [M.VPN_ERR_DEVICE_ACCOUNT_BINDING_FAIL]    = "device account binding failed",
    [M.VPN_ERR_DEVICE_UNAUTHENTICATED]         = "device unauthenticated",
    [M.VPN_ERR_REACH_LOGIN_LIMIT]              = "reach login limit",
    [M.VPN_ERR_UPLOAD_FILE_TOO_LARGE]          = "uploaded file too large (insufficient flash/RAM)",
    [M.VPN_ERR_OPERATE_TOO_FREQUENT]           = "operation too frequent, please try again later",
    [M.VPN_ERR_EXTERNAL_SERVICE_UNAVAILABLE]   = "external service is unavailable",
    [M.VPN_ERR_TAP_S2S_MODE_CONFLICT]          = "function does not work because TAP-S2S Mode is enabled",
    [M.VPN_ERR_PROVIDER_MFA_REQUIRED]          = "two factor authentication required",
    [M.VPN_ERR_PROVIDER_OTP_INVALID]           = "invalid two factor authentication code",
}

M.err_msg = err_msg

return M
